---

base_locale: en
locales: [en]

ignore_unused:
  - decidim.components.emitter.name
  - decidim.admin.forms.file_help.emitter.*

ignore_missing:
  - decidim.participatory_processes.scopes.global
  - decidim.participatory_processes.admin.participatory_processes.form.*
